### ISSUE TITLE
Rspec E2E testing function

### ISSUE THREAD

**Issue by nzerobe** [copiousfreetime/launchy#126]
``` rb
ubuntu@nzerobe-advanced-practice-6895201:~/workspace/docs$ bin/rspec spec/features/blog.spec.rb
Running via Spring preloader in process 24622

Blog management function
  Test blog list
  Test blog creation
  Test blog details
  Test blog list
xprop:  unable to open display ''
xprop:  unable to open display ''
  Testing blog creation (FAILED - 1)

Failures:

  1) Blog management function Testing blog creation
     Failure/Error: save_and_open_page
     
     Launchy::CommandNotFoundError:
       Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new
     # /usr/local/rvm/gems/ruby-2.6.3/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:63:in `browser_cmdline'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:67:in `cmd_and_args'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:78:in `open'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/launchy-2.4.3/lib/launchy.rb:29:in `open'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/capybara-2.18.0/lib/capybara/session.rb:890:in `open_file'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/capybara-2.18.0/lib/capybara/session.rb:761:in `save_and_open_page'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/features/blog.spec.rb:53:in `block (2 levels) in <main>'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
     # /usr/local/rvm/gems/ruby-2.6.3/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'

Finished in 0.49809 seconds (files took 0.25035 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/features/blog.spec.rb:43 # Blog management function Testing blog creation
```
Github URL; `https://github.com/nzerobe/manyo-challenge`

**Comment by copiousfreetime** [comment]
Hi @nzerobe I'm going to need more context on your issue. It looks to me as if you are using `save_and_open_page` with launchy and probably on a system that does  not have a browser application installed.

if you could please add how you are running your code that would help? Are you running it in a CI environment or inside a docker container?

**Comment by copiousfreetime** [comment]
closing as no further information was given
