### ISSUE TITLE
Incompatible with the `debug` gem? (`after_fork': undefined method `open' for #<DEBUGGER__::ProcessGroup)

### ISSUE THREAD

**Issue by lucascaton** [copiousfreetime/launchy#147]
Hi there,

I've found an issue when using `launchy` + `debug` gem (the new official library maintained by the Ruby team: https://github.com/ruby/debug):

```
~/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/launchy-2.5.0/lib/launchy.rb:35:in `rescue in open': Failure in opening uri "file:////project/tmp/letter_opener/1638081050_5918021_32dfe9e/rich.html" with options {}: undefined method `open' for #<DEBUGGER__::ProcessGroup:0x00000001220fd610 @lock_file=nil, @lock_tempfile=#<Tempfile:/var/folders/nr/wrbb5b6s2xlf4hm4gbh0qpyc0000gp/T/ruby-debug-lock-20211128-42041-f2vo3k (closed)>, @m=#<Thread::Mutex:0x00000001127425d0>, @lock_level=0> (Launchy::Error)
```

```
~/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/debug-1.3.4/lib/debug/session.rb:1720:in `after_fork': undefined method `open' for #<DEBUGGER__::ProcessGroup:0x00000001220fd610 @lock_file=nil, @lock_tempfile=#<Tempfile:/var/folders/nr/wrbb5b6s2xlf4hm4gbh0qpyc0000gp/T/ruby-debug-lock-20211128-42041-f2vo3k (closed)>, @m=#<Thread::Mutex:0x00000001127425d0>, @lock_level=0> (NoMethodError)
```

---

Here's the stack I'm using:

- Ruby `3.0.3`
- Rails `6.1.4.1`
- `debug` gem version `1.3.4`
- `letter_opener` gem version `1.7.0`
- `launchy` gem version `2.5.0`

**Comment by copiousfreetime** [comment]
@lucascaton Thanks for the report. Do you have a sample snippet of code I can use to help debug this?

**Comment by lucascaton** [comment]
Sorry @copiousfreetime, false alarm.

I found the following in my initializer and it was causing the issue. 🤦‍♂️

```ruby
Kernel.alias_method(:original_open, :open)
Kernel.remove_method(:open)
```

---

One curious fact is that this issue only happens when I have both `launchy` and `debug` gems in the project! 🤔
