### ISSUE TITLE
Launchy:CommandNotFoundError

### ISSUE THREAD

**Issue by Aufree** [copiousfreetime/launchy#78]
When i run heroku open ,I get this 

```
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new (Launchy::CommandNotFoundError)
    Backtrace:   /usr/local/lib/ruby/gems/2.0.0/gems/launchy-2.4.2/lib/launchy/applications/browser.rb:63:in `browser_cmdline'
                 /usr/local/lib/ruby/gems/2.0.0/gems/launchy-2.4.2/lib/launchy/applications/browser.rb:67:in `cmd_and_args'
                 /usr/local/lib/ruby/gems/2.0.0/gems/launchy-2.4.2/lib/launchy/applications/browser.rb:78:in `open'
                 /usr/local/lib/ruby/gems/2.0.0/gems/launchy-2.4.2/lib/launchy.rb:29:in `open'
                 /usr/local/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/helpers.rb:328:in `block in launchy'
                 /usr/local/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/helpers.rb:227:in `action'
                 /usr/local/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/helpers.rb:326:in `launchy'
                 /usr/local/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/command/apps.rb:338:in `open'
                 /usr/local/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/command.rb:218:in `run'
                 /usr/local/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/cli.rb:28:in `start'
                 /usr/local/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/bin/heroku:17:in `<top (required)>'
                 /usr/local/bin/heroku:23:in `load'
                 /usr/local/bin/heroku:23:in `<main>'

    Command:     heroku open
    Plugins:     heroku-accounts
    Version:     heroku-gem/3.3.0 (i686-linux) ruby/2.0.0
```

My default browser is chrome,System is lucid32 
I tried run launchy - d ,then i get these

```
root@lucid32:/vagrant/paul# launchy -d
ERROR: Failure in opening uri nil with options {:debug=>true}: undefined method `to_hash' for nil:NilClass
LAUNCHY_DEBUG: ERROR: Failure in opening uri nil with options {:debug=>true}: undefined method `to_hash' for nil:NilClass
LAUNCHY_DEBUG: /usr/local/lib/ruby/gems/2.0.0/gems/launchy-2.4.2/lib/launchy.rb:34:in `rescue in open'
LAUNCHY_DEBUG: /usr/local/lib/ruby/gems/2.0.0/gems/launchy-2.4.2/lib/launchy.rb:40:in `open'
LAUNCHY_DEBUG: /usr/local/lib/ruby/gems/2.0.0/gems/launchy-2.4.2/lib/launchy/cli.rb:68:in `good_run'
LAUNCHY_DEBUG: /usr/local/lib/ruby/gems/2.0.0/gems/launchy-2.4.2/lib/launchy/cli.rb:86:in `run'
LAUNCHY_DEBUG: /usr/local/lib/ruby/gems/2.0.0/gems/launchy-2.4.2/bin/launchy:4:in `<top (required)>'
LAUNCHY_DEBUG: /usr/local/bin/launchy:23:in `load'
LAUNCHY_DEBUG: /usr/local/bin/launchy:23:in `<main>'
Try `launchy --help' for more information.
```

**Comment by kevinhq** [comment]
For others who also get this problem when working on a virtualbox (my case is on c9 with ec2 machine), just run: `sudo apt-get install iceweasel`. That will install browsers to the box and fix this error
