### ISSUE TITLE
Unable to find browser - launchy with vagrant virtualbox

### ISSUE THREAD

**Issue by ambshar** [copiousfreetime/launchy#86]
I am getting the error below while using launchy with rspec/capybara.  
I am running it in a vagrant virtualbox.
Ruby version 2.0.0p451
launchy version 2.4.2

thanks

```
ERROR: Unable to find a browser command. If this is unexpected, Please rerun with env
ironment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at
 https://github.com/copiousfreetime/launchy/issues/new
```

testing with  -d option -->

``````
vagrant@lucid32:/vagrant$ launchy -d http://www.cnn.com
LAUNCHY_DEBUG: URI parsing pass 1 : http://www.cnn.com -> {:scheme=>"http", :user=>ni
l, :password=>nil, :host=>"www.cnn.com", :port=>nil, :path=>"", :query=>nil, :fragmen
t=>nil}
LAUNCHY_DEBUG: Checking if class Launchy::Application::Browser is the one for handles
?(http://www.cnn.com)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one fo
r matches?(linux-gnu)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for
 matches?(linux-gnu)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Nix is the one for ma
tches?(linux-gnu)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_c
urrent_engine?(ruby)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one fo
r matches?(linux-gnu)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for
 matches?(linux-gnu)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Nix is the one for ma
tches?(linux-gnu)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_c
urrent_engine?(ruby)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::NixDesktopEnvironment::Kde is the o
ne for is_current_desktop_environment?()}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::NixDesktopEnvironment::Gnome is the
 one for is_current_desktop_environment?()}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::NixDesktopEnvironment::Xfce is the
one for is_current_desktop_environment?()}
LAUNCHY_DEBUG: Launchy::Application : Unable to find `xprop' in /home/vagrant/.rbenv/
versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugins/r
uby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sbin,
 /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/bin
LAUNCHY_DEBUG: Checking if class Launchy::Detect::NixDesktopEnvironment::Xdg is the o
ne for is_current_desktop_environment?()}
LAUNCHY_DEBUG: Launchy::Application : Unable to find `xdg-open' in /home/vagrant/.rbe
nv/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugin
s/ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sb
in, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/b
in
LAUNCHY_DEBUG: Checking if class Launchy::Detect::NixDesktopEnvironment::NotFound is
the one for is_current_desktop_environment?()}
LAUNCHY_DEBUG: Launchy::Application : Unable to find `firefox' in /home/vagrant/.rben
v/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugins
/ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sbi
n, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/bi
n
LAUNCHY_DEBUG: Launchy::Application : Unable to find `seamonkey' in /home/vagrant/.rb
env/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugi
ns/ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/s
bin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/
bin
LAUNCHY_DEBUG: Launchy::Application : Unable to find `opera' in /home/vagrant/.rbenv/
versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugins/r
uby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sbin,
 /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/bin
LAUNCHY_DEBUG: Launchy::Application : Unable to find `mozilla' in /home/vagrant/.rben
v/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugins
/ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sbi
n, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/bi
n
LAUNCHY_DEBUG: Launchy::Application : Unable to find `netscape' in /home/vagrant/.rbe
nv/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugin
s/ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sb
in, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/b
in
LAUNCHY_DEBUG: Launchy::Application : Unable to find `galeon' in /home/vagrant/.rbenv
/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugins/
ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sbin
, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/bin

LAUNCHY_DEBUG: Checking if class Launchy::Detect::NixDesktopEnvironment::Kde is the o
ne for is_current_desktop_environment?()}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::NixDesktopEnvironment::Gnome is the
 one for is_current_desktop_environment?()}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::NixDesktopEnvironment::Xfce is the
one for is_current_desktop_environment?()}
LAUNCHY_DEBUG: Launchy::Application : Unable to find `xprop' in /home/vagrant/.rbenv/
versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugins/r
uby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sbin,
 /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/bin
LAUNCHY_DEBUG: Checking if class Launchy::Detect::NixDesktopEnvironment::Xdg is the o
ne for is_current_desktop_environment?()}
LAUNCHY_DEBUG: Launchy::Application : Unable to find `xdg-open' in /home/vagrant/.rbe
nv/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugin
s/ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sb
in, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/b
in
LAUNCHY_DEBUG: Checking if class Launchy::Detect::NixDesktopEnvironment::NotFound is
the one for is_current_desktop_environment?()}
LAUNCHY_DEBUG: Launchy::Application : Unable to find `firefox' in /home/vagrant/.rben
v/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugins
/ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sbi
n, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/bi
n
LAUNCHY_DEBUG: Launchy::Application : Unable to find `seamonkey' in /home/vagrant/.rb
env/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugi
ns/ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/s
bin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/
bin
LAUNCHY_DEBUG: Launchy::Application : Unable to find `opera' in /home/vagrant/.rbenv/
versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugins/r
uby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sbin,
 /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/bin
LAUNCHY_DEBUG: Launchy::Application : Unable to find `mozilla' in /home/vagrant/.rben
v/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugins
/ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sbi
n, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/bi
n
LAUNCHY_DEBUG: Launchy::Application : Unable to find `netscape' in /home/vagrant/.rbe
nv/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugin
s/ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sb
in, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/b
in
LAUNCHY_DEBUG: Launchy::Application : Unable to find `galeon' in /home/vagrant/.rbenv
/versions/2.0.0-p451/bin, /home/vagrant/.rbenv/libexec, /home/vagrant/.rbenv/plugins/
ruby-build/bin, /home/vagrant/.rbenv/shims, /home/vagrant/.rbenv/bin, /usr/local/sbin
, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /opt/vagrant_ruby/bin

ERROR: Unable to find a browser command. If this is unexpected, Please rerun with env
ironment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at
 https://github.com/copiousfreetime/launchy/issues/new
LAUNCHY_DEBUG: ERROR: Unable to find a browser command. If this is unexpected, Please
 rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option an
d file a bug at https://github.com/copiousfreetime/launchy/issues/new
LAUNCHY_DEBUG: /home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/laun
chy-2.4.2/lib/launchy/applications/browser.rb:63:in `browser_cmdline'
LAUNCHY_DEBUG: /home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/laun
chy-2.4.2/lib/launchy/applications/browser.rb:67:in `cmd_and_args'
LAUNCHY_DEBUG: /home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/laun
chy-2.4.2/lib/launchy/applications/browser.rb:78:in `open'
LAUNCHY_DEBUG: /home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/laun
chy-2.4.2/lib/launchy.rb:29:in `open'
LAUNCHY_DEBUG: /home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/laun
chy-2.4.2/lib/launchy/cli.rb:68:in `good_run'
LAUNCHY_DEBUG: /home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/laun
chy-2.4.2/lib/launchy/cli.rb:86:in `run'
LAUNCHY_DEBUG: /home/vagrant/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/laun
chy-2.4.2/bin/launchy:4:in `<top (required)>'
LAUNCHY_DEBUG: /home/vagrant/.rbenv/versions/2.0.0-p451/bin/launchy:23:in `load'
LAUNCHY_DEBUG: /home/vagrant/.rbenv/versions/2.0.0-p451/bin/launchy:23:in `<main>'
Try `launchy --help' for more information
```.
``````

**Comment by jendiamond** [comment]
I have the same problem. I am so happy to find this entry even though it is closed because now I can at least feel okay about commenting out the save_and_open_page line.

**Comment by copiousfreetime** [comment]
@jendiamond I'd like to have an appropriate notification output to the console or similar in these situations. What would have made your day better and removed the need to search for this issue? I've opened a ticket to discuss this (#95) feel free to chime in there

Also, if you could tell me about the environment you are using, I'd be happy to do what I can to get an appropriate message added.
